RestorantOrder/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DataAccess;
using Entities.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//using RestorantOrder.Data;
using RestorantOrder.Models;

namespace RestorantOrder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RestaurantArea
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tables.ToListAsync());
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RestorantOrder/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
//using RestorantOrder.Data;
using Entities.Models;
using DataAccess;

namespace RestorantOrder.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .SingleOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            var Order =  new Order();
            Order.WaiterId = "Voltis Agolli";
            Order.Items = _context.Items.ToList();

            return View(Order);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,WaiterId,TotalOrderPrice,Date")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.SingleOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,WaiterId,TotalOrderPrice,Date")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .SingleOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.SingleOrDefaultAsync(m => m.Id == id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

RestorantOrder/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RestorantOrder/Views/Home/Index.cshtml
@model IEnumerable<Entities.Models.Table>
@{
    ViewData["Title"] = "Restaurant Area";
}

<h2>@ViewData["Title"]</h2>

@await Html.PartialAsync("_AreaPartial", Model)

RestorantOrder/Views/Home/_AreaPartial.cshtml
@using Entities.Models;
@model IEnumerable<Table>


<title>Bootstrap Example</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="container">

    <ul class="nav nav-tabs">
        <li><a id="IndoorTab" data-toggle="tab" href="#IndoorId">Indoor</a></li>
        <li><a id="OutdoorTab" data-toggle="tab" href="#OutdoorId">Outdoor</a></li>
        <li><a id="GardenTab" data-toggle="tab" href="#GardenId">Garden</a></li>
    </ul>

    <div class="tab-content">
        <div id="IndoorId" class="tab-pane fade">
            <h3 class="text-center">Indoor Tables</h3>
            @foreach (var table in Model)
            {
                if (table.Area == Area.Indoor)
                {
                    <div class=" col-md-2">
                        @Html.ActionLink($"Table {table.Id} Create A New Order", "Create", "Orders", null, new { @class = "btn btn-success btn-large" })
                    </div>
                    <div class="col-md-1"></div>
                }
            }
        </div>
        <div id="OutdoorId" class="tab-pane fade">
            <h3 class="text-center">Outdoor Tables</h3>
            @foreach (var table in Model)
            {
                if (table.Area == Area.Outdoor)
                {
                    <div class=" col-md-2">
                        @Html.ActionLink($"Table {table.Id} Create A New Order", "Create", "Orders", null, new { @class = "btn btn-success btn-large" })
                    </div>
                    <div class="col-md-1"></div>

                }
            }
        </div>
        <div id="GardenId" class="tab-pane fade">
            <h3 class="text-center">Garden Tables</h3>
            @foreach (var table in Model)
            {
                if (table.Area == Area.Garden)
                {
                    <div class=" col-md-2">
                        @Html.ActionLink($"Table {table.Id} Create A New Order", "Create", "Orders", null, new { @class = "btn btn-success btn-large" })
                    </div>
                    <div class="col-md-1"></div>

                }
            }
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#IndoorTab").click();
    });
</script>